import {
  FcReddit,
  FcOldTimeCamera,
  FcIdea,
  FcLandscape,
  FcSlrBackSide,
  FcSportsMode,
  FcVoicePresentation,
  FcMusic,
  FcLikePlaceholder,
  FcQuestions,
  FcRules,
  FcAssistant,
  FcConferenceCall,
  FcGallery,
  FcHeadset,
  FcReading,
  FcSelfie,
  FcSpeaker,
  FcSms,
  FcHome,
  FcFullTrash,
  FcLinux,
  FcStatistics,
  FcReadingEbook,
} from 'react-icons/fc';
import { MdSportsKabaddi } from 'react-icons/md';

const ICON_DATA = [
  { id: 1, icon: <FcLinux />, name: '파티룸' },
  { id: 2, icon: <FcAssistant />, name: '연습실' },
  { id: 3, icon: <FcOldTimeCamera />, name: '촬영스튜디오' },
  { id: 4, icon: <FcReading />, name: '스터디룸' },
  { id: 5, icon: <FcMusic />, name: '공연장' },
  { id: 6, icon: <FcHome />, name: '공유주방' },
  { id: 7, icon: <MdSportsKabaddi />, name: '댄스연습실' },
  { id: 8, icon: <FcSlrBackSide />, name: '렌탈스튜디오' },
  { id: 9, icon: <FcConferenceCall />, name: '회의실' },
  { id: 10, icon: <FcSelfie />, name: '라이브방송' },
  { id: 11, icon: <FcFullTrash />, name: '카페' },
  { id: 12, icon: <FcHeadset />, name: '보컬연습실' },
  { id: 13, icon: <FcIdea />, name: '호리존' },
  { id: 14, icon: <FcQuestions />, name: '세미나실' },
  { id: 15, icon: <FcRules />, name: '컨퍼런스' },
  { id: 16, icon: <FcLikePlaceholder />, name: '스몰웨딩' },
  { id: 17, icon: <FcReddit />, name: '악기연습실' },
  { id: 18, icon: <FcLandscape />, name: '실외촬영' },
  { id: 19, icon: <FcVoicePresentation />, name: '강의실' },
  { id: 20, icon: <FcSportsMode />, name: '운동시설' },
  { id: 21, icon: <FcGallery />, name: '갤러리' },
  { id: 22, icon: <FcSpeaker />, name: '녹음실' },
  { id: 23, icon: <FcReadingEbook />, name: '독립오피스' },
  { id: 24, icon: <FcStatistics />, name: '코워킹오피스' },
  { id: 25, icon: <FcSms />, name: '비상주서비스' },
];

export default ICON_DATA;
